# set in the main CLI; declared here for completness
ACTION=""
ASSUME_DEFAULTS=""
PROJECT_ID=""
ORGANIZATION_ID=""
# end cli option globals

VALID_ACTIONS="build init run update-web"
INTRAWEB_SETTINGS="INTRAWEB_DEFAULT_ORGANIZATION_ID INTRAWEB_PROJECT_PREFIX"

INTRAWEB_DB="${HOME}/.intraweb"
INTRAWEB_CACHE="${INTRAWEB_DB}/cache"
INTRAWEB_TMP_ERROR="${INTRAWEB_CACHE}/temp-error.txt"

INTRAWEB_SETTINGS_FILE="${INTRAWEB_DB}/settings.sh"
